# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='party_image',
            field=models.ImageField(blank=True, upload_to='users/party_logo'),
        ),
    ]
