# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile'),
        ('dashboard', '0002_auto_20170827_1643'),
    ]

    operations = [
    ]
